### ISSUE TITLE
Wrong order for "Now and next"

### ISSUE THREAD

**Issue by MagicFab** [Wilm0r/giggity#20]
Thank you for this great tool.
I am attending DebConf17 and noticed when looking at "Now and then" some events aren't in the right order.

For example for today I see:

Now:
13:00 - 14:00 Lunch

Next:
15:30-15:50 - An apt Talk
17:00-17:50 Building a PKI and PGP Clean room
16:20-1700 Coffee break
14:30-15:15 Bits from the DPL
15:30-16:20 The past, present and future of Debian Games

It should actually show:

Next:
14:30-15:15 Bits from the DPL
15:30-15:50 - An apt Talk
15:30-16:20 The past, present and future of Debian Games
16:20-1700 Coffee break
17:00-17:50 Building a PKI and PGP Clean room

Perhaps the ability to group by room / track would also be useful here.

**Comment by Wilm0r** [comment]
Ridiculously late, my apologies. If you're still interested in this feature (which coincidentally got requested by someone else the very same month or possibly even day (!) at OHM2017), I'm interested in views.

The current approach tries to preserve the ordering of rooms. And at many events, the rooms are kind of ordered from main track to the tiniest ones, so there's some kind of importance in there that I was trying to stick to.

OTOH things get confusing yes. Especially in examples like yours, with hours in between. Would you not expect (assuming you do FOSDEM here) Janson and the 2-3 other large rooms to be more prominently shown?

And if we're going for sorting, I guess why limit to one per room? I'd then show the next talk for every room, but also subsequent ones up to an hour away from $now, since that's a more sensible thing to do as well then, agreed?

Maybe this should be a setting..

**Comment by MagicFab** [comment]
I have no idea, it's been a long time. I just remember the order displayed was wrong or not intuitive.

Based on my initial report perhaps some sort of tree grouping and display would be useful.

**Comment by Wilm0r** [comment]
This is in 2.0: It's using this sorting now, and includes possibly a few subsequent talks in a room as well if they're also <1h away.
