### ISSUE TITLE
Dark or/and Black Theme

### ISSUE THREAD

**Issue by tasmo** [Wilm0r/giggity#42]
Fortunately I'm running a phone with an AMOLED display. Many apps have a power saving black based theme.

Might it be possible to implement theming in Giggity or use the devices default colors from themes like from Substratum?

**Comment by Iizuki** [comment]
This would indeed be neat. I was just comparing the different FOSDEM schedule apps, and the lack of dark mode is pretty much the only thing keeping me from saying that this one is the best.

**Comment by Wilm0r** [comment]
Ooh, so I did look into this I think 3y ago when I was having a pretty productive Giggity dev sprint, but gave up and at the time also didn't care too much.

But indeed now I raise an eyebrow myself when I see an app that doesn't implement dark mode. (Some with maaaaany more users than Giggity will ever have.) I need to do this indeed. Time to figure out how, it seemed tedious at the time... :(

**Comment by Wilm0r** [comment]
BTW no way I can get this done in time before FOSDEM :( Looked during the weekend, supposedly this should be easy if one uses a `DayNight` theme variant, but it didn't seem to make a difference in Giggity so I need to dig into Android API (Material, AppCompat, all that crap) a little more. :(

**Comment by Iizuki** [comment]
No sweat. I appreciate you picking this up in the first place! (And unfortunately I know even less about mobile development..)

**Comment by Wilm0r** [comment]
Hah, yeah it's not quite my main field of work either. It's a fun hobby but in the end honestly this is hardly any better than web development, which I've last done when .... PHP? Ew.

Anyway, this does look kinda promising now!

![image](https://user-images.githubusercontent.com/6828117/216795423-e23156bc-6309-4484-897e-3755c6eccf87.png)

I'm terrible with colours but I'll do my best. It's a little harder without AppCompat or other crap that would bump the Giggity APK up from 400KB to 2MB again.

**Comment by Wilm0r** [comment]
OK, block schedule and event dialog darkened too now.

<img src="https://user-images.githubusercontent.com/6828117/217501989-27d3f412-d10b-4be5-bb71-6bb3d6be3655.png" width="40%"> <img src="https://user-images.githubusercontent.com/6828117/217502544-e3c30c5f-35c8-4ecd-8f9f-59a411068503.png" width="40%">

**Comment by zuphilip** [comment]
@Wilm0r This looks very interesting! Is it finished and when can it be used in the official version from F-Droid?

One feedback I have based on the pictures here: Maybe you want to consider to color the lines forming the grid in white or at least lighter. Especially in [this picture](https://user-images.githubusercontent.com/6828117/217501989-27d3f412-d10b-4be5-bb71-6bb3d6be3655.png) it is a little hard to see when exactly a specific talk starts because I can't recognize any line to the times on top.

**Comment by Wilm0r** [comment]
Yeah you're right. I'll try brighter first, convention in these dark colour schemes does seem to be 90% greyscale from what I can tell.

How about this? 
![image](https://user-images.githubusercontent.com/6828117/226148322-056a7703-7895-4f69-8e9b-14880fec526b.png)

**Comment by zuphilip** [comment]
Yes, that is better. Thank you!

**Comment by Wilm0r** [comment]
> @Wilm0r This looks very interesting! Is it finished and when can it be used in the official version from F-Droid?
> 
So I've added it to the Open Testing graph but on the Play Store: https://play.google.com/apps/testing/net.gaast.giggity I guess switching over would be hard though since they don't use my signing key for their APKs, you'd end up losing your settings. I'll see whether F-Droid supports separate beta tracks too. And probably I'll just release it properly pretty soon anyway.

**Comment by Wilm0r** [comment]
HEAD now tagged with version number 2.1 so hopefully F-Droid will pick this up within the next week.
