### ISSUE TITLE
Filter tracks by date

### ISSUE THREAD

**Issue by seirl** [Wilm0r/giggity#88]
In FOSDEM Companion, there's a way to only show the tracks of a single day. It's very useful when you want to make your plans for the next day, for instance.

**Comment by Wilm0r** [comment]
Hey! I remember we spoke about this at FOSDEM, and since then have looked at the code a little bit for this change, but it may be more complicated than you'd reasonably expect. But I'll give it a shot as part of the ~major rework I'm doing.

**Comment by Wilm0r** [comment]
So about this: I'm nearing the end of a pretty thorough redo and rethink of the program. (I can send you an .apk if you're interested.) And the tracks view is one of the last bits I've not changed yet.

And what I wonder is, is there a good reason for it being a different view from the timetable at all?

The timetable is already divided by day, no surprises there. But also it's one continuous view per day, while the tracklist is just that, a list, linking you through to a per-track list of events/talks.

Would it make more sense to you if it was just like the current timetable view, just keyed by track (and indeed per day)?

Given your request is already for splitting by day, I suspect your answer will be yes. :-)

**Comment by Wilm0r** [comment]
Oh yes, one idea from @insomniacslk yesterday: add checkboxes or hide icons or so in the track view so it can be used to quickly eliminate tracks/themes that you're not interested in.

I do like this as an idea for making the tracks view meaningfully different instead of just a very mild variant of the timetable view.

**Comment by seirl** [comment]
> Would it make more sense to you if it was just like the current timetable view, just keyed by track (and indeed per day)?

I don't quite remember the usability issue I had, but this solution sounds like it would solve the problem I reported!

**Comment by Wilm0r** [comment]
This is more or less what I have in mind. Pretty much the new-style timetable layout but keyed by track instead of room.

I think some may still want to browse all talks (all days) in a track, wondering whether use a similar UI like Google Photos, where you can tap to drop-down on the title to see the rest.

![Screenshot_1571595292](https://user-images.githubusercontent.com/6828117/67164035-07b5a980-f32b-11e9-8d80-9839de91300f.png)

**Comment by Wilm0r** [comment]
This is in 2.0.
