### ISSUE TITLE
Stop replacing menu.json title with schedule file title

### ISSUE THREAD

**Issue by chrysn** [Wilm0r/giggity#96]
When an ICS file is added via a menu JSON that has a title, it is initially shown in the list with the given title. When the event is later loaded, some calendar files (at least [the IETF one](https://datatracker.ietf.org/meeting/104/agenda.ics)) later show their calendar URI in the list instead of the given name.

My impression is that this affects calendars that don't have a X-WR-CALDESC/X-WR-CALNAME set, and that the fallback sequence is "X-WR-* / URI / JSON-name", while it should better be "X-WR-* / JSON-name / URI" or even "JSON-name / X-WR-* / URI".

**Comment by Wilm0r** [comment]
Yeah I was thinking of letting the menu.json title override any title that may come from the schedule. Never actually implemented it because ... unsure why. But yeah I probably should.

(I think mostly because figuring out that titles from non-menu.json confs *should* be used means buggy heuristics.)

**Comment by Wilm0r** [comment]
Fixed in the quagmire branch, hopefully I'll turn that into a release soonish.

**Comment by Wilm0r** [comment]
This is in 2.0
